#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

OUT_FILE="${1:-README.md}"

echo "# [**T**oday **I** **L**earned](https://mihaeu.github.io/til) 🤯

*(For usage refer to [USAGE.md](USAGE.md))*
" > "${OUT_FILE}"
cat 201* >> "${OUT_FILE}"
echo "
Generated on $(date)" >> "${OUT_FILE}"

[[ $OUT_FILE = "README.md" ]] && git add README.md
