#!/usr/bin/env php
<?php

if (!isset($argv[1])) {
    echo 'Usage: php generate.php [SUBJECT]' . PHP_EOL;
    exit(1);
}

$argv[0] = '';
$args = trim(implode(' ', $argv));
$filename = date('Y-m-d').'_'.str_replace(' ', '-', strtolower($args)).'.md';
echo 'Run:' . PHP_EOL . PHP_EOL . 'vi ' . $filename . PHP_EOL;

if (file_exists(__DIR__ . '/' . $filename)) {
    echo PHP_EOL . 'File already exists! Not overwriting.' . PHP_EOL;
    exit(1);
}
file_put_contents(
    $filename,
    '# '.$args.PHP_EOL.PHP_EOL
);
echo exec('git -C "' . __DIR__ . '" add "' . $filename . '"');
