#!/usr/bin/env bash

source "$HOME/dotfiles/scripts/helpers"

./compile /tmp/til-pre-commit-check.md

TIMESTAMP_DIFF_OFFSET=4
let "DIFF_COUNT = $(diff README.md /tmp/til-pre-commit-check.md | wc -l) - $TIMESTAMP_DIFF_OFFSET"

if [[ $DIFF_COUNT -lt 0 ]]
then
    _error "README out of date, please compile ..."
    exit 1
fi

_success "README looks fine, commiting ..."
